#!/bin/bash

adduser --disabled-password --gecos "" $S3_IDENTITY
echo "$S3_IDENTITY:$S3_CREDENTIAL" | chpasswd 

echo $S3_IDENTITY:$S3_CREDENTIAL > /s3credentials
chmod 600 /s3credentials

mkdir -p /mnt/s3
s3fs $S3_BUCKET /mnt/s3 -o passwd_file=/s3credentials -o allow_other -o uid=$(id -u $S3_IDENTITY)
rm -vfr /home/$S3_IDENTITY
ln -s /mnt/s3 /home/$S3_IDENTITY

echo "SFTP user: $S3_IDENTITY"
echo "S3 Bucker: $S3_BUCKET"
echo "S3 Key: $S3_KEY"
echo "Ready to accept connections..."
exec /usr/sbin/sshd -D
